# Generated by Django 2.2.2 on 2019-07-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=500)),
                ('pdf', models.FileField(upload_to='pdf')),
            ],
        ),
    ]
