# Generated by Django 2.2.2 on 2019-07-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townplan', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('msg', models.TextField(max_length=350)),
            ],
        ),
    ]
